#!/usr/bin/env python3
"""
Turns the kernel's bitmap font into a real webfont.

font.c holds 95 glyphs as 16 bytes each, one byte per scanline, bit 7 the
leftmost pixel. This walks that table, merges lit pixels into rectangles and
emits them as TrueType contours, so the website is set in the *same bytes*
the operating system draws with -- not a font that merely looks similar.

    python3 scripts/mkwebfont.py [path/to/font.c]

Writes public/fonts/cigaretteos.woff2 (and .ttf alongside it).
"""

import re
import sys
from pathlib import Path

from fontTools.fontBuilder import FontBuilder
from fontTools.pens.ttGlyphPen import TTGlyphPen

FONT_W, FONT_H = 8, 16
FIRST = 0x20                # first glyph in the table: space
PX = 64                     # font units per pixel

# The generator pads 4 blank rows above and below the 8-row glyph -- that is
# line spacing for the kernel console, and it must NOT be part of the em, or
# the letters render at half the requested font-size. So the em spans only
# rows 3..12: 8 rows above the baseline, 2 below for descenders.
#
# One glyph pixel is therefore font-size / 10. Use sizes that are multiples
# of 10 (10, 20, 30, 40...) and every pixel lands on whole device pixels.
BASELINE_ROW = 11
ASCENT = 8 * PX             # 512
DESCENT = 2 * PX            # 128
UPM = ASCENT + DESCENT      # 640


def read_glyphs(path: Path):
    """Pull the 16-byte rows out of the generated C table."""
    rows = []
    for line in path.read_text().splitlines():
        m = re.match(r"\s*\{\s*(0x[0-9a-fA-F]{2}(?:\s*,\s*0x[0-9a-fA-F]{2})*)\s*\}", line)
        if m:
            rows.append([int(b, 16) for b in m.group(1).split(",")])
    if len(rows) != 95:
        raise SystemExit(f"expected 95 glyphs, found {len(rows)}")
    return rows


def rects(bitmap):
    """Merge lit pixels into rectangles: horizontal runs first, then stack
    vertically adjacent runs that span the same columns. Fewer contours
    means a smaller font and no hairline seams between pixels."""
    runs = []                      # (row, x0, x1) half-open
    for r, bits in enumerate(bitmap):
        x = 0
        while x < FONT_W:
            if bits & (0x80 >> x):
                x0 = x
                while x < FONT_W and (bits & (0x80 >> x)):
                    x += 1
                runs.append([r, x0, x, 1])   # last field: height in rows
            else:
                x += 1

    merged = []
    for run in runs:
        for m in merged:
            if m[1] == run[1] and m[2] == run[2] and m[0] + m[3] == run[0]:
                m[3] += 1
                break
        else:
            merged.append(run)
    return merged


def build_glyph(bitmap):
    pen = TTGlyphPen(None)
    for row, x0, x1, h in rects(bitmap):
        left = x0 * PX
        right = x1 * PX
        top = (BASELINE_ROW - row) * PX
        bottom = (BASELINE_ROW - row - h) * PX
        # clockwise, so the nonzero winding rule fills it
        pen.moveTo((left, bottom))
        pen.lineTo((left, top))
        pen.lineTo((right, top))
        pen.lineTo((right, bottom))
        pen.closePath()
    return pen.glyph()


def main():
    src = Path(sys.argv[1]) if len(sys.argv) > 1 else Path.home() / "cigaretteOS" / "font.c"
    if not src.exists():
        raise SystemExit(f"cannot find {src} — pass the path to font.c")

    bitmaps = read_glyphs(src)

    order = [".notdef"]
    glyphs = {".notdef": TTGlyphPen(None).glyph()}
    cmap = {}
    metrics = {".notdef": (FONT_W * PX, 0)}

    for i, bm in enumerate(bitmaps):
        code = FIRST + i
        name = f"uni{code:04X}"
        order.append(name)
        glyphs[name] = build_glyph(bm)
        cmap[code] = name
        metrics[name] = (FONT_W * PX, 0)

    fb = FontBuilder(UPM, isTTF=True)
    fb.setupGlyphOrder(order)
    fb.setupCharacterMap(cmap)
    fb.setupGlyf(glyphs)
    fb.setupHorizontalMetrics(metrics)
    fb.setupHorizontalHeader(ascent=ASCENT, descent=-DESCENT)
    fb.setupNameTable({
        "familyName": "cigaretteOS",
        "styleName": "Regular",
        "uniqueFontIdentifier": "cigaretteOS Regular; generated from font.c",
        "fullName": "cigaretteOS Regular",
        "psName": "cigaretteOS-Regular",
        "version": "Version 1.0",
        "manufacturer": "generated by scripts/mkwebfont.py",
        "description": "The cigaretteOS kernel console font, 8x16, drawn by hand.",
    })
    fb.setupOS2(sTypoAscender=ASCENT, sTypoDescender=-DESCENT,
                usWinAscent=ASCENT, usWinDescent=DESCENT,
                achVendID="CIGA", fsType=0)
    fb.setupPost(isFixedPitch=1)

    out = Path("public/fonts")
    out.mkdir(parents=True, exist_ok=True)

    ttf = out / "cigaretteos.ttf"
    fb.save(str(ttf))
    print(f"  {ttf}  {ttf.stat().st_size / 1024:.1f} KB")

    # WOFF needs only zlib. WOFF2 needs brotli, which may not be installed.
    for flavor in ("woff2", "woff"):
        try:
            fb.font.flavor = flavor
            path = out / f"cigaretteos.{flavor}"
            fb.save(str(path))
            print(f"  {path}  {path.stat().st_size / 1024:.1f} KB")
        except Exception as e:
            print(f"  {flavor} skipped ({type(e).__name__})")

    print(f"  {len(bitmaps)} glyphs, U+0020..U+{FIRST + len(bitmaps) - 1:04X}")


if __name__ == "__main__":
    main()
